HS_detector/blog/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from wtforms.widgets import TextArea


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', widget=TextArea())
    picture = FileField('browse', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Post')

HS_detector/blog/main/routes.py
from flask import render_template,request,Blueprint
from blog.users.forms import SearchForm
from blog.models import Post

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)#pagination and post order
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

HS_detector/blog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request,abort,Blueprint
from blog import db
from blog.posts.forms import PostForm
from blog.models import Post, Reports
from flask_login import current_user,login_required
from blog.posts.utils import save_picture, get_picture_path
from flask_mail import Message
from blog.finalmodel import get_predictions, ocr
from PIL import Image
import cv2
import numpy as np



posts = Blueprint('posts', __name__)

#route for new post
@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            checktitle = get_predictions(request.form['title'])
            checkcontent = get_predictions(request.form['content'])
            
            # picture_path = get_picture_path(form.picture.data)
            # pictureText = ocr(picture_path)
            # checkImage = get_predictions(pictureText)

            if(checktitle == 0 or checkcontent == 0 ):
                flash("It looks like you are trying to submit hateful content. We are strictly against online hate speech", 'danger')
            elif(checktitle == 1 or checkcontent == 1 ):
                flash("We strongly recommend not to post offensive content to our platform", 'warning')
                post = Post(title=form.title.data, content=form.content.data, post_image=picture_file, author=current_user)
                db.session.add(post)
                db.session.commit()
                flash('Your post has been created!', 'success')
                return redirect(url_for('main.home'))
            else:
                post = Post(title=form.title.data, content=form.content.data, post_image=picture_file, author=current_user)
                db.session.add(post)
                db.session.commit()
                flash('Your post has been created!', 'success')
                return redirect(url_for('main.home'))
        else:
            checktitle = get_predictions(request.form['title'])
            checkcontent = get_predictions(request.form['content'])

            if(checktitle == 0 or checkcontent == 0):
                flash("It looks like you are trying to submit hateful content. We are strictly against online hate speech", 'danger')
            elif(checktitle == 1 or checkcontent == 1):
                flash("We strongly recommend not to post offensive content to our platform", 'warning')
                post = Post(title=form.title.data, content=form.content.data, author=current_user)
                db.session.add(post)
                db.session.commit()
                flash('Your post has been created!', 'success')
                return redirect(url_for('main.home'))
            else:
                post = Post(title=form.title.data, content=form.content.data, author=current_user)
                db.session.add(post)
                db.session.commit()
                flash('Your post has been created!', 'success')
                return redirect(url_for('main.home'))
            
        
    #photo = url_for('static', filename = 'post_images/' + post.post_image)
    return render_template('create_post.html',legend="Post Something on BlogWELL", title="Create a New Post", form=form)

#route for view post
@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

#update post
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            checktitle = get_predictions(request.form['title'])
            checkcontent = get_predictions(request.form['content'])
            
            # picture_path = get_picture_path(form.picture.data)
            # pictureText = ocr(picture_path)
            # checkImage = get_predictions(pictureText)

            if(checktitle == 0 or checkcontent == 0 ):
                flash("It looks like you are trying to submit hateful content. We are strictly against online hate speech", 'danger')
            elif(checktitle == 1 or checkcontent == 1 ):
                flash("We strongly recommend not to post offensive content to our platform", 'warning')
                post = Post(title=form.title.data, content=form.content.data, post_image=picture_file, author=current_user)
                db.session.add(post)
                db.session.commit()
                flash('Your post has been created!', 'success')
                return redirect(url_for('main.home'))
            else:
                post = Post(title=form.title.data, content=form.content.data, post_image=picture_file, author=current_user)
                db.session.add(post)
                db.session.commit()
                flash('Your post has been created!', 'success')
                return redirect(url_for('main.home'))
        else:
            checktitle = get_predictions(request.form['title'])
            checkcontent = get_predictions(request.form['content'])

            if(checktitle == 0 or checkcontent == 0):
                flash("It looks like you are trying to submit hateful content. We are strictly against online hate speech", 'danger')
            elif(checktitle == 1 or checkcontent == 1):
                flash("We strongly recommend not to post offensive content to our platform", 'warning')
                post = Post(title=form.title.data, content=form.content.data, author=current_user)
                db.session.add(post)
                db.session.commit()
                flash('Your post has been created!', 'success')
                return redirect(url_for('main.home'))
            else:
                post = Post(title=form.title.data, content=form.content.data, author=current_user)
                db.session.add(post)
                db.session.commit()
                flash('Your post has been created!', 'success')
                return redirect(url_for('main.home'))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    # if form.validate_on_submit():
    #     post.title = form.title.data
    #     post.content = form.content.data
    #     post.post_image = save_picture(form.picture.data)
    #     db.session.commit()
    #     flash('Your post has been updated', 'success')
    #     return redirect(url_for('posts.post', post_id=post.id))
    # elif request.method == 'GET':
    #     form.title.data = post.title
    #     form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Edit Your Post')
    
#delete post
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted', 'success')
    return redirect(url_for('main.home'))

@posts.route('/post/<int:post_id>/report', methods=['GET', 'POST'])
@login_required
def report_post(post_id):
    post = Post.query.get_or_404(post_id)
    reason = request.form.get('reason')
    description = request.form.get('description')

    if post:
        report = Reports(author=current_user, post_id=post_id, reason=reason, description=description)
        db.session.add(report)
        db.session.commit()
        flash('Your report was sent successfully. We will take the necessary action', 'success')
    else:
        flash('post does not exist', category='error')
    
    return redirect(url_for('posts.post', post_id=post_id))

HS_detector/blog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

HS_detector/blog/templates/admin_register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {{ form.hidden_tag() }}<!--adds a CSRF token-->
            <fieldset class="form-group">
                 <legend class="border-bottom mb-4 font-weight-bold">Create an Admin Account</legend>
                 <!-- username -->
                 <div class="form-group">
                    {{ form.username.label(class="form-control-label font-weight-bold") }}

                    <!-- if there are errors in input -->
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        <!-- no errors -->
                        {{ form.username(class="form-control form-control") }}
                    {% endif %}  
                 </div>

                 <!-- email -->
                 <div class="form-group">
                    {{ form.email.label(class="form-control-label font-weight-bold") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        <!-- no errors -->
                        {{ form.email(class="form-control form-control") }}
                    {% endif %} 
                 </div>

                 <!-- password -->
                 <div class="form-group">
                    {{ form.password.label(class="form-control-label font-weight-bold") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        <!-- no errors -->
                        {{ form.password(class="form-control form-control") }}
                    {% endif %} 
                 </div>

                 <!-- confirm password -->
                 <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label font-weight-bold") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        <!-- no errors -->
                        {{ form.confirm_password(class="form-control form-control") }}
                    {% endif %} 
                 </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account?<a href="{{ url_for('users.login') }}" class="ml-2" style="color:aliceblue">Sign In</a>
        </small>
    </div>
{% endblock content %}

HS_detector/blog/templates/change_password.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {{ form.hidden_tag() }}<!--adds a CSRF token-->
            <fieldset class="form-group">
                 <legend class="border-bottom mb-4">Password Reset</legend>
                 <!-- username -->
                 

                 <!-- new password -->
                 <div class="form-group">
                    {{ form.password.label(class="form-control-label font-weight-bold") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        <!-- no errors -->
                        {{ form.password(class="form-control") }}
                    {% endif %} 
                 </div>
                  <!--confirm new password  -->
                  <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label font-weight-bold") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        <!-- no errors -->
                        {{ form.confirm_password(class="form-control") }}
                    {% endif %} 
                 </div> 
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>

        </form>
    </div>
    
{% endblock content %}

HS_detector/blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

     <!-- Required meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
     <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
     
    {% if title %}
        <title>BlogWELL - {{ title }}</title>
    {% else %}
        <title>BlogWELL</title>
    {% endif %}

</head>

<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/home">BlogWELL</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                {% if current_user.is_admin == True %}
                  <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
                  <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
                  <a class="nav-item nav-link" href="/admin">Admin</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
                  <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
                {% endif %}   
              </div>

              <!-- Search bar -->
              <form action="{{ url_for('users.search') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="input-group">
                  <div class="form-outline">
                    <input type="search" name="searched" id="form1" class="form-control" placeholder="search" />
                  </div>
                  <button type="submit" class="btn btn-primary btn-search">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              </form>

              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %} <!-- if logged in display logout on nav bar-->
                  <a class="nav-item nav-link" href="{{url_for('posts.new_post')}}">New Post</a>
                  <a class="nav-item nav-link" href="{{url_for('users.account')}}">Account</a>
                  <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
                  <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8 mx-auto">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <script>
                      setTimeout(function() {
                        $('.alert').fadeOut('fast');
                    }, 5000);
                    </script>
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}

            
          </div>
          <!-- <div class="col-md-4">
             <div class="content-section">
               {% block sidebar %}
                <h3>Our Sidebar</h3>
              {% endblock %} -->
              <!-- <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div> -->
          </div>
          
        </div>
      </main>

      

      
    
      
    

    <!-- Optional JavaScript -->
    <script src="https://kit.fontawesome.com/ed732df593.js" crossorigin="anonymous"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
</body>

    
</html>

HS_detector/blog/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file)}}" class="rounded-circle article-img" alt="">
        <div class="media-body">
            <div class="d-flex justify-content-between">
                <div class="article-metadata">
                    <!-- link to the user_posts page -->
                    <a class="mr-2 uname" href="{{url_for('users.user_posts', username=post.author.username )}}" >{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                    <!-- update and delete -->
                    {% if post.author == current_user %}
                        <div>
                            <a href="{{ url_for('posts.update_post', post_id=post.id) }}" class="btn btn-secondary btn-sm mt-1 mb-1">Edit</a>
                            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                        </div>
                    {% endif %}
                </div>
                <div>
                    <!-- <input type="button" value="report" data-toggle="modal" data-target="#reportModal">data-toggle="modal" data-target="#reportModal"</i>
                    <button data-toggle="modal" data-target="#reportModal"><i class="fa-solid fa-circle-exclamation"></i></button> -->
                    <a href="#" data-toggle="modal" data-target="#reportModal"><i class="fa-solid fa-circle-exclamation"></i></a>
                </div>
            </div>
            
            
            <h2 class="article-title font-weight-bold">{{ post.title }}</a></h2>
            {% if post.post_image %}
                <div><p class="article-content">{{ post.content }}</p></div>
                <div class="post-pic"><img src="{{url_for('static', filename = 'post_images/' + post.post_image)}}" alt="" height="auto" width="500px"></div>
            {% else %}
                <div><p class="article-content">{{ post.content }}</p></div>
            {% endif %}

            <!-- like button -->
            <div>
                <span id="likes-count-{{post.id}}">{{post.likes|length}}</span>
                {% if current_user in post.likes|map(attribute="author")|list %}
                    <i class="fa-solid fa-thumbs-up fa-2x" id="likes-button-{{post.id}}" onclick="like({{post.id}})"></i></a>
                {% else %}
                    <i class="fa-regular fa-thumbs-up fa-2x" id="likes-button-{{post.id}}" onclick="like({{post.id}})"></i></a> 
                {% endif %}
            </div>

            <!-- display comments -->
            <!-- expand/collapse the comments for the specific post -->
            <div class="collapse" id="comments-{{post.id}}">
                <div class="card card-body" id="comments-expanded-{{post.id}}">
                   {% for comment in post.comments %}
                       <div class="">
                           <div>
                               <a href="{{url_for('users.user_posts', username=comment.author.username )}}" class="uname">{{comment.author.username}}</a>: {{comment.text}}
                           </div>
                           <div>
                               <small class="text-muted">{{comment.date_posted.strftime('%Y-%m-%d')}}</small>
                               <!-- delete comments -->
                               {% if current_user.id == comment.user_id or current_user.id == post.user_id %}
                                   <div class="btn-group">
                                        <a href="#" style="width: 20px; height: 20px;" style="border: 2px solid black;"  data-toggle="dropdown" >
                                            <i class="fa-regular fa-trash-can"></i>
                                        </a>
                                       <ul class="dropdown-menu">
                                           <li>
                                               <a href="/delete-comment/{{comment.id}}" class="dropdown-item">delete</a>
                                           </li>
                                       </ul>
                                   </div>
                               {% endif %}
                           </div>
                       </div><br>
                   {% endfor %}
               </div>
           </div>

        
        <!-- toggle the comments section -->
        <p class="card-text">
            {% if post.comments|length > 0 %}
            <a data-toggle="collapse" href="#comments-{{post.id}}" role="button" aria-expanded="false">
                <small>View {{post.comments|length }} comments</small>
            </a>     
            {% else%}
            <small class="text-muted">No comments to display</small>
            {% endif %}
        </p>
        
        <br>
        <!-- add a comment form -->
        <form action="/comment/{{post.id}}" class="input-group mb-3" method="POST">
            <div class="mr-2">
                <input type="text" name="text" id="text" class="form-control" placeholder="add your comment here" style="width: 500px;"/>
            </div>
            <div>
                <button type="submit" class="btn btn-rounded" style="border: 2px solid black;"><i class="fa-solid fa-paper-plane"></i></button>
            </div>
        </form>

            
    </article>  

    <!--delete post Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h3 class="modal-title fs-5" id="deleteModalLabel">Delete your Post?</h3>
            <button type="button" class="btn btn-close" data-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">cancel</button>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input type="submit" class="btn btn-danger" value="Delete">
            </form>
            </div>
        </div>
        </div>
    </div>

        <!-- Report post modal -->
    <div class="modal" tabindex="-1" role="dialog" id="reportModal">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title">Report Post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
            <!-- Report form -->
            <form action="{{url_for('posts.report_post', post_id=post.id)}}" method="post">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    <div class="form-check">
                        <input type="radio" name="reason" id="Hate_speech" value="Hate Speech">
                        <label for="Hate_speech">Hate Speech</label><br>
                        <input type="radio" name="reason" id="false" value="False Information">
                        <label for="false">False Information</label><br>
                        <input type="radio" name="reason" id="violance" value="Violance">
                        <label for="violance">Violance</label>
                    </div>
                    <div class="form-description">
                        <input type="text" class="form-control" name="description" id="description" placeholder="Describe the situation(Optional)">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Report</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
            </div>
        </div>
        </div>
    </div>

{% endblock content %}
    
<!-- <i class="bi bi-pencil-square">
    <a href="{{ url_for('update_post', post_id=post.id)}}"></a>
</i>
<i class="bi bi-trash">

</i> -->

HS_detector/blog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {{ form.hidden_tag() }}<!--adds a CSRF token-->
            <fieldset class="form-group">
                 <legend class="border-bottom mb-4">Password Reset</legend>
                 <!-- username -->
                 

                 <!-- email -->
                 <div class="form-group">
                    {{ form.email.label(class="form-control-label font-weight-bold") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        <!-- no errors -->
                        {{ form.email(class="form-control form-control") }}
                    {% endif %} 
                 </div>   
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>

        </form>
    </div>
    
{% endblock content %}